---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: builder0
    groups:
      - builder_bin
    image: ubuntu:bionic
  - name: specer0
    groups:
      - builder_spec
    image: ubuntu:bionic
  - name: validator0
    image: jrei/systemd-ubuntu:18.04
    groups:
      - bootnode
      - validator
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/sbin/init'
    network_mode: host
    environment:
      container: docker
  - name: validator1
    image: jrei/systemd-ubuntu:18.04
    groups:
      - validator
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/sbin/init'
    network_mode: host
    environment:
      container: docker
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        substrate_repository: false
        substrate_binary_url: 'https://github.com/paritytech/polkadot/releases/download/v0.7.20/polkadot'
        substrate_repository_version: ''
        substrate_network_id: local_testnet
        # substrate_chain: /home/subuser/tmp/gantree-validator/spec/chainSpecRaw.raw
        substrate_chain_argument: 'false'
        substrate_use_default_spec: 'true'
        substrate_bin_name: polkadot
        substrate_node_name: gantree-fetched
        substrate_user: subuser
        substrate_group: subgroup
        substrate_rpc_port: 9933
        substrate_options: []
        substrate_bootnode_argument: []
        gantree_control_working: /tmp/gantree-control
        gantree_root: ../../../../../
      builder_bin:
        gantree_working: /tmp/gantree-build-bin
      builder_spec:
        gantree_working: /tmp/gantree-build-spec
      validator:
        gantree_working: /home/subuser/tmp/gantree-validator
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
