---
- name: modify disk
  gcp_compute_disk:
    name: 'disk-instance'
    size_gb: 50
    source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: "{{ state }}"
  register: disk
