- hosts: all
  roles:
    - role: validator-env-gantree
  become: yes

- hosts: builder_bin
  roles:
    - mock-build-bin
  become: yes

- hosts: validator:builder_spec
  strategy: free
  roles:
    - validator-push-bin
  become: yes

- hosts: localhost
  roles:
    - control-prepare

- hosts: validator
  serial: 1 # NOTE(ryan): to avoid weird collision on pulling the keys to host
  roles:
    - validator-gen-keys

- hosts: builder_spec
  roles:
    - role: builder-build-spec
      when: 'substrate_use_default_spec|default(false)|bool == false and substrate_chain_argument|default(false)|bool == false'

- hosts: bootnode # NOTE(ryan): currently only supports 1
  roles:
    - role: bootnode-collect-ip
      when: 'substrate_use_default_spec|default(false)|bool == false and substrate_chain_argument|default(false)|bool == false'

- hosts: validator
  roles:
    - role: validator-push-spec
      when: 'substrate_use_default_spec|default(false)|bool == false and substrate_chain_argument|default(false)|bool == false'

- hosts: validator
  roles:
    - validator-service

- hosts: validator
  roles:
    - validator-key-insert

- hosts: validator
  roles:
    - validator-service-restart
