- name: ensure curl
  become: yes
  apt:
    name: curl

- name: grab keys
  shell: |
    if [ {{ item }} = gran ]; then
      crypto="ed25519"
    else
      crypto="sr25519"
    fi
    inspect_result=$(cat /home/{{ substrate_user }}/mnemonic | xargs --null /usr/local/bin/subkey --${crypto} inspect)
    public_key=$(echo -n "${inspect_result}" | grep "Public key" | cut -d':' -f2 | tr -d '[:space:]')
    mnemonic=$(cat /home/{{ substrate_user }}/mnemonic)

    printf "${public_key}"
    printf "${mnemonic}"

    curl http://localhost:9933 -H "Content-Type:application/json" -d \
      "{ \
        \"jsonrpc\":\"2.0\", \
        \"id\":1, \
        \"method\":\"author_insertKey\", \
        \"params\": [ \
          \"{{ item }}\", \
          \"${mnemonic}\", \
          \"${public_key}\" \
        ] \
      }"
  args:
    executable: /bin/bash
  loop:
    - aura
    - gran
    - babe
    - imol
    - para
    - audi
  register: keys

- name: debug keys
  debug:
    var: keys
