---
- name: ec2 instance info
  delegate_to: localhost
  ec2_instance:
    state: "{{ state }}"
    region: "{{ region }}"
    filters:  # NOTE(ryan): default filter borks with character limit exceeded
      "tag:Name": "inst-{{ instance_name }}"
      "tag:not_terminated": "true"
  register: ec2inst_res_all

- name: set ec2inst_res fact
  delegate_to: localhost
  set_fact:
    ec2inst_res: "{{ ec2inst_res_all.instances[0] | default('not-found') }}"
