---
- name: find ubuntu amis
  delegate_to: localhost
  ec2_ami_info:
    region: "{{ region }}"
    owners:
      - 099720109477 # Canonical
    filters:
      name: "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
  register: ubuntu_amis

- name: get latest ami
  delegate_to: localhost
  set_fact:
    latest_ami: >
      {{ ubuntu_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- import_tasks: 2_vpc_subnet_info.yml
- import_tasks: 2_security_group_info.yml

- name: ec2 instance
  delegate_to: localhost
  ec2_instance:
    wait: yes
    state: "{{ state }}"
    name: "inst-{{ instance_name }}"
    region: "{{ region }}"
    key_name: "{{ ssh_key_name }}"
    instance_type: "{{ instance_type }}"
    subnet_id: "{{ vpcsn_res.id | default(omit) }}"
    security_group: "{{ secgroup_res.group_id | default(omit) }}"
    filters:  # NOTE(ryan): default filter borks with character limit exceeded
      "tag:Name": "inst-{{ instance_name }}"
      "tag:not_terminated": "true"
    tags:
      # because we can't really filter on the instance-state properly
      # change the flag when we terminate
      gantree: "managed"
      group_name: "{{ instance_name }}"
      not_terminated: "{{ 'false' if state == 'absent' else 'true' }}"
    image_id: "{{ latest_ami.image_id | default(omit) }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ volume_size }}"
          delete_on_termination: true
  register: inst_state

- name: set ec2 not_terminated tag
  delegate_to: localhost
  ec2_tag:
    region: "{{ region }}"
    resource: '{{ item.instance_id }}'
    tags:
      not_terminated: "{{ 'false' if state == 'absent' else 'true' }}"
  with_items: "{{ inst_state.instances }}"
  failed_when: false
  no_log: yes
