---
- name: refresh security group info
  delegate_to: localhost
  ec2_group_info:
    region: "{{ region }}"
    filters:
      tag:Name: "SG {{ instance_name }}"
  register: secgroup_res_all
  no_log: yes

- name: set secgroup_res fact
  delegate_to: localhost
  set_fact:
    secgroup_res: "{{ secgroup_res_all.security_groups[0] }}"
