---
- name: refresh vpc subnet
  delegate_to: localhost
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "vpcsn-{{ instance_name }}"
  register: vpcsn_res_all
  no_log: yes

- name: set vpcsn_res fact
  delegate_to: localhost
  set_fact:
    vpcsn_res: "{{ vpcsn_res_all.subnets[0] }}"
