---
- name: create host bin directory
  delegate_to: localhost
  file:
    path: '{{ gantree_control_working }}/bin'
    state: directory
  become: no

- name: download polkadot binary
  delegate_to: localhost
  get_url:
    url: '{{ polkadot_binary_url | quote }}'
    checksum: '{{ polkadot_binary_checksum | quote }}'
    dest: '{{ gantree_control_working }}/bin/{{ substrate_bin_name }}'
    validate_certs: no #todo figure out why this is needed and fix
  become: no
